### ISSUE TITLE
slog-rsync doesn't compile with rust-nightly-2017-07-08 or rust-nightly-2017-07-09

### ISSUE THREAD

**Issue by lakinwecker** [slog-rs/async#2]
Unsure if this is an issue in slog-async or a regression in the rust nightly.

Errors look like: https://gist.github.com/lakinwecker/72839075f2a671750e89b4be190641de

**Comment by lakinwecker** [comment]
nightly-2017-07-07 works.

**Comment by dpc** [comment]
It works on stable, AFAIK, so it's a Rust nightly bug? Could you report rust language github issue?

**Comment by lakinwecker** [comment]
Done.

**Comment by lakinwecker** [comment]
Seems it's already been fixed. Sorry for using this as a support forum. I should have run `cargo update`
